2.7.1
{
    "filename": "gcin-2.7.1.tar.xz",
    "md5": "beb8cb87e288b1edaebc7ed955254c9d",
    "sha1": "16e549f5e602c7834dcc35875e375f1e660a627d",
    "sha256": "d51dda364402d977a6837464ece18ebe526e4a8291698728435bf5097457aa09"
}

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -14,7 +14,6 @@ if [ "$1" = "-h" -o "$1" = "--help" -o "$1" = "-help" ]; then
     echo "  --use_qt3=N    : disable Qt3 immodule"
     echo "  --use_qt4=N    : disable Qt4 immodule"
     echo "  --use_gtk3=N   : disable GTK+ 3.x immodule"
-    echo "  --gcinlibdir=dir   : runtime path of gcin's *.so"
     exit
 fi
 
@@ -36,7 +35,7 @@ if [ $? = 0 ]; then
   FREEBSD=1
 fi
 
-SO_FLAGS="-Wl,--as-needed -shared"
+SO_FLAGS="-shared"
 MAC_OS=0
 uname | grep Darwin > /dev/null 2> /dev/null
 if [ $? = 0 ]; then
@@ -84,41 +83,23 @@ for opt do
   --use_qt4*) use_qt4=`echo $opt | cut -d '=' -f 2`
   ;;
   --use_gtk3*) use_gtk3=`echo $opt | cut -d '=' -f 2`
-  ;;
-  --gcinlibdir*) gcinlibdir=`echo $opt | cut -d '=' -f 2`
   esac
 done
 
 echo "prefix: $prefix"
 
-for i in gtk+-3.0 gtk+-2.0
-do
-  echo -n ".... Testing $i : "
-  GTKINC=`pkg-config --cflags $i 2>/dev/null`
 
-  if [ $? != 0 ]; then
-    echo "not found"
-    continue
-  fi
+GTK=gtk+-2.0
 
-  GTKLDFLAGS=`pkg-config --libs $i`
-  if [ $? = 0 ]; then
-    GTK=$i
-    echo "found"
-    break
-  fi
-done
+echo -n ".... Testing $GTK : "
 
-if [ $GTK = '' ]; then
-  echo "According to pkg-config, GTK 2.0 or 3.0 WAS NOT FOUND."
-  echo "please install rpm/package libgtk+2.0_0-devel or libgtk+3.0_0-devel"
+GTKINC=`pkg-config --cflags $GTK`
+
+if [ $? != 0 ]; then
+  echo "$GTK or above required --cflags"
   rm -f config.mak
-  exits
+  exit -1;
 fi
-
-echo "$GTK will be used."
-echo "GTKINC: $GTKINC"
-echo "GTKLDFLAGS: $GTKLDFLAGS"
 
 ## problem in MacOS, by candyz
 if [ $MAC_OS = 1 ]; then
@@ -139,7 +120,16 @@ if [ ! -x /bin/bash ]; then
 fi
 
 
+GTKLDFLAGS=`pkg-config --libs $GTK`
 
+if [ $? != 0 ]; then
+  echo "$GTK or above required --libs"
+  echo "please install rpm/package libgtk+2.0_0-devel"
+  rm -f config.mak
+  exit -1;
+else
+  echo " found."
+fi
 
 echo -n ".... Testing anthy    :  "
 USE_ANTHY=`pkg-config --libs anthy`
@@ -173,10 +163,8 @@ fi
 
 
 LIB='lib'
-if [ -d /usr/lib64 -a -d /lib64 ]; then
-LIB='lib64'
-# for fedora 64bit
-GTK_QUERY_IM_64='-64'
+if [ -d /usr/lib64foo -a -d /lib64 ]; then
+LIB='lib64foo'
 fi
 
 QT_IM='N'
@@ -245,21 +233,9 @@ optdir=/opt
 GCIN_VERSION=`cat VERSION.gcin`
 sed -e "s/__gcin_version__/$GCIN_VERSION/" < gcin.spec.in > gcin.spec
 
-if [ -z "$gcinlibdir" ]; then
-  gcinlibdir=$libdir/gcin
-fi
-
 if [ $QT_IM = 'N' ]; then
   mv gcin.spec gcin.spec.tmp
   grep -v qt3/plugins/inputmethods gcin.spec.tmp > gcin.spec
-else
-  for i in /usr/share/qt/bin/moc /usr/lib/qt/bin/moc /usr/lib64/qt/bin/moc /usr/lib/qt3/bin/moc /usr/share/qt3/bin/moc /usr/lib64/qt3/bin/moc
-  do
-    [ ! -x $i ] && continue
-    QT_MOC=$i
-    echo "QT_MOC=$QT_MOC"
-    break;
-  done
 fi
 
 
@@ -269,9 +245,9 @@ if [ $QT4_IM = 'N' ]; then
   mv gcin.spec gcin.spec.tmp
   grep -v qt4/plugins/inputmethods gcin.spec.tmp > gcin.spec
 else
-  for i in /usr/share/qt4/bin/moc /usr/lib/qt4/bin/moc /usr/lib64/qt4/bin/moc /usr/bin/moc
+  for i in /usr/share/qt4/bin/moc /usr/lib/qt4/bin/moc /usr/lib64/qt4/bin/moc
   do
-    [ -x $i ] && QT4_MOC=$i && echo "QT4_MOC=$QT4_MOC"
+	[ -x $i ] && QT4_MOC=$i
   done
 fi
 
@@ -280,7 +256,7 @@ if [ $USE_ANTHY = 'Y' ] || [ $USE_CHEWING = 'Y' ]; then
   BUILD_MODULE='Y'
 fi
 
-OPTFLAGS="-g -O"
+OPTFLAGS="-O"
 
 if [ -z $CC ]; then
   CC=gcc
@@ -300,9 +276,9 @@ echo "bindir_r=$bindir" >> config.mak
 echo "datadir=\$(DESTDIR)$datadir" >> config.mak
 echo "datadir_r=$datadir" >> config.mak
 echo "libdir=\$(DESTDIR)$libdir" >> config.mak
-echo "gcinlibdir=\$(DESTDIR)$gcinlibdir" >> config.mak
+echo "gcinlibdir=\$(libdir)/gcin" >> config.mak
 echo "includedir=\$(DESTDIR)$includedir" >> config.mak
-echo "LDFLAGS=-Wl,--as-needed $GTKLDFLAGS -lX11 -ldl -lm" >> config.mak
+echo "LDFLAGS=$GTKLDFLAGS -lX11 -ldl -lm" >> config.mak
 echo "GCIN_VERSION=$GCIN_VERSION" >> config.mak
 echo "GCIN_TABLE_DIR=\$(datadir_r)/gcin/table" >> config.mak
 echo "GCIN_OGG_DIR=\$(datadir_r)/gcin/ogg" >> config.mak
@@ -333,9 +309,7 @@ echo "USE_ANTHY=$USE_ANTHY" >> config.mak
 echo "USE_CHEWING=$USE_CHEWING" >> config.mak
 echo "USE_GCB=$use_gcb" >> config.mak
 echo "BUILD_MODULE=$BUILD_MODULE" >> config.mak
-echo "GTK_QUERY_IM_64=$GTK_QUERY_IM_64" >> config.mak
 [ $QT4_IM = 'Y' ] && echo "QT4_MOC=$QT4_MOC" >> config.mak
-[ $QT_IM = 'Y' ] && echo "QT_MOC=$QT_MOC" >> config.mak
 
 if [ $prefix = /usr/local ]; then
   echo "gcin_ld_run_path=$PWD:\$(gcinlibdir)" >> config.mak
